name: DemocracyDJ
options:
  bundleIdPrefix: com.jeffschmitz
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: YES

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.17.0"
  Shared:
    path: ../shared

targets:
  DemocracyDJ:
    type: application
    platform: iOS
    sources:
      - path: DemocracyDJ
        excludes:
          - "**/.gitkeep"
    info:
      path: DemocracyDJ/Info.plist
      properties:
        NSLocalNetworkUsageDescription: "Democracy DJ uses the local network to connect devices for collaborative music voting."
        NSBonjourServices:
          - "_democracy-dj._tcp"
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffschmitz.DemocracyDJ
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: ComposableArchitecture
      - package: Shared

  DemocracyDJTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DemocracyDJTests
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffschmitz.DemocracyDJTests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: DemocracyDJ

schemes:
  DemocracyDJ:
    build:
      targets:
        DemocracyDJ: all
        DemocracyDJTests: [test]
    run:
      config: Debug
    test:
      config: Debug
      targets:
        - DemocracyDJTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
