name: DemocracyDJ
options:
  bundleIdPrefix: com.jeffschmitz
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "16.0"
  developmentLanguage: en

settings:
  base:
    SWIFT_VERSION: "6.0"
    SWIFT_STRICT_CONCURRENCY: complete
    ENABLE_USER_SCRIPT_SANDBOXING: YES

packages:
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: "1.17.0"
  Shared:
    path: ../shared

targets:
  DemocracyDJ:
    type: application
    platform: iOS
    sources:
      - path: DemocracyDJ
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffschmitz.DemocracyDJ
        INFOPLIST_GENERATION_MODE: GeneratedFile
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: ""
    dependencies:
      - package: ComposableArchitecture
      - package: Shared

  DemocracyDJTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: DemocracyDJTests
        excludes:
          - "**/.gitkeep"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.jeffschmitz.DemocracyDJTests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: DemocracyDJ
